export { AssistantPage } from "./assistant/AssistantPage";
export { AudioToTextPage } from "./audio-to-text/AudioToTextPage";
export { ImageGenerationPage } from "./image-generation/ImageGenerationPage";
export { ImageTunningPage } from "./image-tunning/ImageTunningPage";
export { OrthographyPage } from "./orthography/OrthographyPage";
export { ProsConsStreamPage } from "./pros-cons-stream/ProsConsStreamPage";
export { ProsConsPage } from "./pros-cons/ProsConsPage";
export { TextToAudioPage } from "./text-to-audio/TextToAudioPage";
export { TranslatePage } from "./translate-page/TranslatePage";
